name: $(GitVersion.FullSemVer)
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: Release

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - docs/*
      - README.md

steps:
  - checkout: self
    clean: true
    persistCredentials: true

  - task: UseGitVersion@5
    displayName: GitVersion
    inputs:
      versionSpec: '5.x'

  - script: dotnet pack -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)\out -p:Version=$(GitVersion.SemVer)
    displayName: 'dotnet pack'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)\out
      ArtifactName: out
